language: ruby
#naresh
rvm:
  - 1.9.3
  - jruby-19mode
  - jruby-head

jdk:
  - openjdk6
  - openjdk7

services:
  - rabbitmq

sudo: false

cache: bundler

matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: jruby-head
      jdk: openjdk6
  allow_failures:
    - rvm: jruby-head
      jdk: openjdk7
